{
  "formatVersion": "1.1",
  "component": {
    "group": "FLib",
    "module": "flib",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "flib-unspecified.aar",
          "url": "flib-unspecified.aar",
          "size": 2131,
          "sha512": "6bee88098e9895d1ac21448c3178e3646638874dd57f75ca45278e4b1291bbcfc3af64fe74e3e79dfb8697f6376b8c91225b422a2d888b6152047201d0f9e3cc",
          "sha256": "fd7c25ae8f171b90c7c6ff6974210619982914d941148aa2cd6edb817a2c1537",
          "sha1": "2836ca18d14d536ba16ca6f8d907fe6c6839094e",
          "md5": "4bafafe1d3f30f270f9ac4864528a707"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "flib-unspecified.aar",
          "url": "flib-unspecified.aar",
          "size": 2131,
          "sha512": "6bee88098e9895d1ac21448c3178e3646638874dd57f75ca45278e4b1291bbcfc3af64fe74e3e79dfb8697f6376b8c91225b422a2d888b6152047201d0f9e3cc",
          "sha256": "fd7c25ae8f171b90c7c6ff6974210619982914d941148aa2cd6edb817a2c1537",
          "sha1": "2836ca18d14d536ba16ca6f8d907fe6c6839094e",
          "md5": "4bafafe1d3f30f270f9ac4864528a707"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flib-unspecified-sources.jar",
          "url": "flib-unspecified-sources.jar",
          "size": 904,
          "sha512": "6913524e689a0a2a85b7796572ddfc8884e466c11c0a36183204fa4a37c8f2dbc6f5db743562221011fb9553201d931af82c04260bc0fcf135b2403934a71163",
          "sha256": "d51ff69141b2934baccc92a455dd4ecd144cd760776b3fdc04b0b10f904f34e6",
          "sha1": "401c45579b91d3ae6ff075fd739fc5c5505d16b3",
          "md5": "230dfdf5e3408a16d2181ab9a1396253"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flib-unspecified-javadoc.jar",
          "url": "flib-unspecified-javadoc.jar",
          "size": 263212,
          "sha512": "fcf9c04562abc5f0c798bd3732987c79c169f64b5f939299afe8845890dd51c59fa0f9b88cf723f1fdc4791a32be4e26e81dceb832c5e16fe45857fff8b512c9",
          "sha256": "fdaf47b26c8ae5a4d219ed6bafe6a5dda8aa4d333bf7b6f49fb2b3bfe38b7f35",
          "sha1": "eb131be3934568eb0cf57802fa45f6ff4758e1ad",
          "md5": "9e8ef7d6190ce6136a2eabb67efb47c2"
        }
      ]
    }
  ]
}
