{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fatherofapps",
    "module": "fpublic",
    "version": "1.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "fpublic-1.8.aar",
          "url": "fpublic-1.8.aar",
          "size": 1897,
          "sha512": "ffacf39fe7a132f864918df4396a1b830e574fc6a113aec4d4b9f26c85aec7d54ac69aecf16c085dad2df8629ae15d7de7de61b39a4b24597a5c50183c21990e",
          "sha256": "ac220e18a21b93169c4139a2bc2fd8e376656d6dbf97a93208f5d0e067eaa3bd",
          "sha1": "c74b78c5c30167ba285ba0e9c10dffff47b59969",
          "md5": "295f580419d71cfe7e3604faae317ea3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "fpublic-1.8.aar",
          "url": "fpublic-1.8.aar",
          "size": 1897,
          "sha512": "ffacf39fe7a132f864918df4396a1b830e574fc6a113aec4d4b9f26c85aec7d54ac69aecf16c085dad2df8629ae15d7de7de61b39a4b24597a5c50183c21990e",
          "sha256": "ac220e18a21b93169c4139a2bc2fd8e376656d6dbf97a93208f5d0e067eaa3bd",
          "sha1": "c74b78c5c30167ba285ba0e9c10dffff47b59969",
          "md5": "295f580419d71cfe7e3604faae317ea3"
        }
      ]
    }
  ]
}
