{
  "formatVersion": "1.1",
  "component": {
    "group": "com.fatherofapps",
    "module": "fpublic",
    "version": "1.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "fpublic-1.6.aar",
          "url": "fpublic-1.6.aar",
          "size": 2113,
          "sha512": "ffd305fde281c5abe7d194cdef7be7ede1d50afac4c8f09e7c7849a560f65ef37723703f4644df0972f01f705f5bd008ed4dff38ab8a2077003fcb7539069785",
          "sha256": "7e20cbdbe44d37a6bb9d22aeff4e718110d19916af7384d9aeb6f835f309b19b",
          "sha1": "f41f75442d2cd08d89d577bdf1a23292babde672",
          "md5": "02728fb2e0fe135faba5dffc9f46258a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "commons-codec",
          "module": "commons-codec",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "fpublic-1.6.aar",
          "url": "fpublic-1.6.aar",
          "size": 2113,
          "sha512": "ffd305fde281c5abe7d194cdef7be7ede1d50afac4c8f09e7c7849a560f65ef37723703f4644df0972f01f705f5bd008ed4dff38ab8a2077003fcb7539069785",
          "sha256": "7e20cbdbe44d37a6bb9d22aeff4e718110d19916af7384d9aeb6f835f309b19b",
          "sha1": "f41f75442d2cd08d89d577bdf1a23292babde672",
          "md5": "02728fb2e0fe135faba5dffc9f46258a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fpublic-1.6-sources.jar",
          "url": "fpublic-1.6-sources.jar",
          "size": 904,
          "sha512": "6913524e689a0a2a85b7796572ddfc8884e466c11c0a36183204fa4a37c8f2dbc6f5db743562221011fb9553201d931af82c04260bc0fcf135b2403934a71163",
          "sha256": "d51ff69141b2934baccc92a455dd4ecd144cd760776b3fdc04b0b10f904f34e6",
          "sha1": "401c45579b91d3ae6ff075fd739fc5c5505d16b3",
          "md5": "230dfdf5e3408a16d2181ab9a1396253"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "fpublic-1.6-javadoc.jar",
          "url": "fpublic-1.6-javadoc.jar",
          "size": 263212,
          "sha512": "fcf9c04562abc5f0c798bd3732987c79c169f64b5f939299afe8845890dd51c59fa0f9b88cf723f1fdc4791a32be4e26e81dceb832c5e16fe45857fff8b512c9",
          "sha256": "fdaf47b26c8ae5a4d219ed6bafe6a5dda8aa4d333bf7b6f49fb2b3bfe38b7f35",
          "sha1": "eb131be3934568eb0cf57802fa45f6ff4758e1ad",
          "md5": "9e8ef7d6190ce6136a2eabb67efb47c2"
        }
      ]
    }
  ]
}
